# Generated by Django 5.2.6 on 2025-10-18 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIHealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("dictionary", "Dictionary API"),
                            ("thesaurus", "Thesaurus API"),
                            ("translator", "Translation API"),
                            ("random_word", "Random Word API"),
                        ],
                        db_index=True,
                        help_text="Which API this log entry is for",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint called", max_length=255),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, help_text="HTTP status code returned", null=True
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the API call was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if call failed"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this health check occurred",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Health Log",
                "verbose_name_plural": "API Health Logs",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["api_type", "-checked_at"],
                        name="core_apihea_api_typ_8a4d72_idx",
                    ),
                    models.Index(
                        fields=["success", "-checked_at"],
                        name="core_apihea_success_1945c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        db_index=True,
                        help_text="Word that was searched",
                        max_length=200,
                    ),
                ),
                (
                    "searched_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the search occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the searcher", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Browser user agent", max_length=255
                    ),
                ),
                (
                    "found",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the word was found in dictionary",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="API response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the search (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Log",
                "verbose_name_plural": "Search Logs",
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-searched_at"],
                        name="core_search_user_id_db49b4_idx",
                    ),
                    models.Index(
                        fields=["word", "-searched_at"],
                        name="core_search_word_2951d7_idx",
                    ),
                    models.Index(
                        fields=["-searched_at"], name="core_search_searche_3ee4ef_idx"
                    ),
                    models.Index(
                        fields=["found", "-searched_at"],
                        name="core_search_found_43fa55_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TranslationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_text",
                    models.TextField(help_text="Original text to translate"),
                ),
                ("translated_text", models.TextField(help_text="Translated result")),
                (
                    "source_language",
                    models.CharField(
                        db_index=True,
                        help_text="Source language code (e.g., 'en', 'es')",
                        max_length=10,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        db_index=True, help_text="Target language code", max_length=10
                    ),
                ),
                (
                    "translated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the translation occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether translation was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if translation failed"
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Translation API response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "char_count",
                    models.IntegerField(
                        default=0, help_text="Number of characters translated"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the translation (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Log",
                "verbose_name_plural": "Translation Logs",
                "ordering": ["-translated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-translated_at"],
                        name="core_transl_user_id_4eb501_idx",
                    ),
                    models.Index(
                        fields=["source_language", "target_language"],
                        name="core_transl_source__aff3f2_idx",
                    ),
                    models.Index(
                        fields=["-translated_at"], name="core_transl_transla_f79b86_idx"
                    ),
                    models.Index(
                        fields=["success", "-translated_at"],
                        name="core_transl_success_e1fd9e_idx",
                    ),
                ],
            },
        ),
    ]
