# Generated by Django 5.2.6 on 2025-10-18 04:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_searchhistory_userfavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchhistory",
            options={
                "ordering": ["-searched_at"],
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="userdata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Data (Legacy)",
                "verbose_name_plural": "User Data (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="userfavorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Favorite",
                "verbose_name_plural": "User Favorites",
            },
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="user_agent",
            field=models.CharField(
                blank=True, help_text="Browser user agent string", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this favorite was added",
            ),
        ),
        migrations.AddField(
            model_name="userfavorite",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional notes about this word"
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address for anonymous tracking", null=True
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="word",
            field=models.CharField(
                db_index=True,
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="favorite_word",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfavorite",
            name="word",
            field=models.CharField(
                db_index=True,
                help_text="The favorite word (stored in lowercase)",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["ip_address", "-searched_at"],
                name="dictionary__ip_addr_279efc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userfavorite",
            index=models.Index(fields=["word"], name="dictionary__word_9f1eae_idx"),
        ),
    ]
